FROM alpine:3.9.3
LABEL maintainer="ayushpawar21"

#Setting a default value to Argument WELCOME_USER
ARG WELCOME_USER=AAYUSH_PAWAR
RUN echo "Welcome $WELCOME_USER, to Docker World!" > message.txt
CMD cat message.txt
